### ISSUE TITLE
Find a way to embed the weekly calender display on the frontpage

### ISSUE THREAD

**Issue by hhamud** [opensensepw/opensense-landpage#3]

**Comment by ismaventuras** [comment]
I found 2 ways to do this:

1 - integrate discord API and get the scheduled events (https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event)

2 - integrate notion API and fetch the data from notion

IMO point 1 would be better as we don't need to wait notion db to be updated

**Comment by hhamud** [comment]
ok so we going forward we treat the discord as the pseudo database and treat it as our source of truth
